export const navigationItems = [
  ['dashboard', 'Dashboard'],
  ['portal', 'Mein Portal'],
  ['scanner', 'Scanner'],
  ['members', 'Mitglieder'],
  ['fees', 'Beiträge'],
  ['cash', 'Kassa'],
  ['invoices', 'Rechnungen'],
  ['events', 'Events'],
  ['documents', 'Dokumente'],
  ['memberArea', 'Mitgliederbereich'],
  ['media', 'Medien / Presse'],
  ['virtualBastardKnowledge', 'Virtual Bastard Wissen'],
  ['sponsors', 'Sponsoren'],
  ['merch', 'Shop & Fanartikel'],
  ['inventory', 'Inventar'],
  ['parkedModules', 'Geparkte Module'],
  ['admin', 'Admin / Export'],
]
